using System;

namespace TextImageConverter
{
    public class ComposeConfiguraton
    {
        public string SourcePath { get; set; } // specified by user
        public string WorkingPath { get; set; } // automatically generated by OS
        public string SavePath { get; set; } // specified by user
        public long FileLength { get; set; } // automatically calculated depending on SourcePath
        public int? ImgWidth { get; set; } // optionally spcified by user
        public int? ImgHeight { get; set; } // optionally specified by user
        public int? OffsetSeed { get; set; } // optionally specfied by user
        public Random OffsetGenerator { get; set; } // automatically determined depending on OffsetSeed
    }
}
