using System;

namespace TextImageConverter
{
    public abstract class ConfigurationBase
    {
        public string SourcePath { get; set; } // [HV] Specified by user
        public string WorkingPath { get; set; } // [HV] Automatically generated by OS
        public string SavePath { get; set; } // [HV] Specified by user
        public int? OffsetSeed { get; set; } // [HV] Optionally specfied by user
        public Random OffsetGenerator { get; set; } // [HV] Automatically determined depending on OffsetSeed
    }
}
