using System;

namespace TextImageConverter
{
    public class ConfigurationBase
    {
        public string SourcePath { get; set; } // [HV] specified by user
        public string WorkingPath { get; set; } // [HV] automatically generated by OS
        public string SavePath { get; set; } // [HV] specified by user
        public int? OffsetSeed { get; set; } // [HV] optionally specfied by user
        public Random OffsetGenerator { get; set; } // [HV] automatically determined depending on OffsetSeed
    }
}