using System.Drawing;

namespace TextImageConverter
{
    public class DecomposeConfiguration
    {
        public string SourcePath { get; set; } // specified by user
        public string WorkingPath { get; set; } // automatically generated by OS
        public string SavePath { get; set; } // specified by user
        public Bitmap Bitmap { get; set; } // automatically generated depending on SourcePath
        public int ImgWidth { get; set; } // automatically calculated depending on Bitmap
        public int ImgHeight { get; set; } // automatically calculated depending on Bitmap
    }
}
