//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCIIsome.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASCIIsome.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (placeholder for English aboutdetails).
        /// </summary>
        public static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose display language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;xs:element name=&quot;CharSet&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;unbounded&quot; name=&quot;CharInfo&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:attribute name=&quot;GrayscaleIndex&quot; type=&quot;xs:double&quot; use=&quot;required&quot; /&gt;
        ///            &lt;xs:attribute name=&quot;Character&quot; type=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CharSetSchema {
            get {
                return ResourceManager.GetString("CharSetSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose character set....
        /// </summary>
        public static string ChooseCharSet {
            get {
                return ResourceManager.GetString("ChooseCharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose character set.
        /// </summary>
        public static string ChooseCharSetWindowTitle {
            get {
                return ResourceManager.GetString("ChooseCharSetWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;xs:element name=&quot;ASCIIsome.config&quot;&gt;
        ///        &lt;xs:complexType&gt;
        ///            &lt;xs:all&gt;
        ///                &lt;xs:element name=&quot;IsAspectRatioKept&quot; type=&quot;xs:boolean&quot; /&gt;
        ///                &lt;xs:element name=&quot;IsDynamicGrayscaleRangeEnabled&quot; type=&quot;xs:boolean&quot; /&gt;
        ///                &lt;xs:element name=&quot;IsGraysc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConfigSchemaV1 {
            get {
                return ResourceManager.GetString("ConfigSchemaV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CharSet DisplayName=&quot;ASCII symbols&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.00000&quot; Character=&quot; &quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.09771&quot; Character=&quot;!&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.08598&quot; Character=&quot;&amp;quot;&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.26690&quot; Character=&quot;#&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.24652&quot; Character=&quot;$&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.26139 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cs_ASCIISymbols {
            get {
                return ResourceManager.GetString("cs_ASCIISymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CharSet DisplayName=&quot;All 11 charset presets concatenated&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0&quot; Character=&quot; &quot; /&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.01924&quot; Character=&quot;`&quot; /&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.03526&quot; Character=&quot;.&quot; /&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.04805&quot; Character=&quot;-&quot; /&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.05551&quot; Character=&quot;,&quot; /&gt;
        ///  &lt;CharInfo Grayscal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cs_CharSetPresetsConcated {
            get {
                return ResourceManager.GetString("cs_CharSetPresetsConcated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CharSet DisplayName=&quot;Lowercase English alphabets&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.21409&quot; Character=&quot;a&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.26391&quot; Character=&quot;b&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.15864&quot; Character=&quot;c&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.26404&quot; Character=&quot;d&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.21643&quot; Character=&quot;e&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cs_LowercaseEnglishAlphabets {
            get {
                return ResourceManager.GetString("cs_LowercaseEnglishAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CharSet DisplayName=&quot;Lowercase Russian alphabets&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.21409&quot; Character=&quot;а&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.28532&quot; Character=&quot;б&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.23818&quot; Character=&quot;в&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.12600&quot; Character=&quot;г&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.26104&quot; Character=&quot;д&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cs_LowercaseRussianAlphabets {
            get {
                return ResourceManager.GetString("cs_LowercaseRussianAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CharSet DisplayName=&quot;Numerals&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.26270&quot; Character=&quot;0&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.18531&quot; Character=&quot;1&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.19975&quot; Character=&quot;2&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.19922&quot; Character=&quot;3&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.21424&quot; Character=&quot;4&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.19647&quot; Characte [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cs_Numerals {
            get {
                return ResourceManager.GetString("cs_Numerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CharSet DisplayName=&quot;Other symbols in ISO/IEC 8859-5&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.31727&quot; Character=&quot;№&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.26907&quot; Character=&quot;§&quot;/&gt;
        ///&lt;/CharSet&gt;
        ///.
        /// </summary>
        public static string cs_Other8859_5Symbols {
            get {
                return ResourceManager.GetString("cs_Other8859_5Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CharSet DisplayName=&quot;Other lowercase Cyrillic alphabets in ISO/IEC 8859-5&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.30674&quot; Character=&quot;ђ&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.15040&quot; Character=&quot;ѓ&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.18357&quot; Character=&quot;є&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.17880&quot; Character=&quot;ѕ&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.13311&quot; Character=&quot;і&quot;/&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cs_OtherLowercaseCyrillicAlphabets {
            get {
                return ResourceManager.GetString("cs_OtherLowercaseCyrillicAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CharSet DisplayName=&quot;Other uppercase Cyrillic alphabets in ISO/IEC 8859-5&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.24264&quot; Character=&quot;Ђ&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.16226&quot; Character=&quot;Ѓ&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.22168&quot; Character=&quot;Є&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.20835&quot; Character=&quot;Ѕ&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.18173&quot; Character=&quot;І&quot;/&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cs_OtherUppercaseCyrillicAlphabets {
            get {
                return ResourceManager.GetString("cs_OtherUppercaseCyrillicAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CharSet DisplayName=&quot;Shades&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.00000&quot; Character=&quot; &quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.25308&quot; Character=&quot;░&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.50514&quot; Character=&quot;▒&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.75307&quot; Character=&quot;▓&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;1.00000&quot; Character=&quot;█&quot;/&gt;
        ///&lt;/CharSet&gt;
        ///.
        /// </summary>
        public static string cs_Shades {
            get {
                return ResourceManager.GetString("cs_Shades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CharSet DisplayName=&quot;Space and full block&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.00000&quot; Character=&quot; &quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;1.00000&quot; Character=&quot;█&quot;/&gt;
        ///&lt;/CharSet&gt;
        ///.
        /// </summary>
        public static string cs_SpaceAndFullBlock {
            get {
                return ResourceManager.GetString("cs_SpaceAndFullBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CharSet DisplayName=&quot;Uppercase English alphabets&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.21228&quot; Character=&quot;A&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.27039&quot; Character=&quot;B&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.18776&quot; Character=&quot;C&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.25390&quot; Character=&quot;D&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.21602&quot; Character=&quot;E&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cs_UppercaseEnglishAlphabets {
            get {
                return ResourceManager.GetString("cs_UppercaseEnglishAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CharSet DisplayName=&quot;Uppercase Russian alphabets&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;ASCIIsome.Resources.CharSets CharSetSchema.xsd&quot;&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.21229&quot; Character=&quot;А&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.24278&quot; Character=&quot;Б&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.27045&quot; Character=&quot;В&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.14285&quot; Character=&quot;Г&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex=&quot;0.31134&quot; Character=&quot;Д&quot;/&gt;
        ///  &lt;CharInfo GrayscaleIndex [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cs_UppercaseRussianAlphabets {
            get {
                return ResourceManager.GetString("cs_UppercaseRussianAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load character sets from the last configuration. Default character set is loaded. .
        /// </summary>
        public static string DefaultCharSetLoaded {
            get {
                return ResourceManager.GetString("DefaultCharSetLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use dynamic grayscale range.
        /// </summary>
        public static string DynamicGrayscaleRange {
            get {
                return ResourceManager.GetString("DynamicGrayscaleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Empty character set).
        /// </summary>
        public static string EmptyCharSet {
            get {
                return ResourceManager.GetString("EmptyCharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text exported to clipboard successfully. .
        /// </summary>
        public static string ExportedToClipboard {
            get {
                return ResourceManager.GetString("ExportedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to clipboard.
        /// </summary>
        public static string ExportToClipboard {
            get {
                return ResourceManager.GetString("ExportToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image loaded. .
        /// </summary>
        public static string ImageLoaded {
            get {
                return ResourceManager.GetString("ImageLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image height.
        /// </summary>
        public static string ImgHeight {
            get {
                return ResourceManager.GetString("ImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image width.
        /// </summary>
        public static string ImgWidth {
            get {
                return ResourceManager.GetString("ImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        public static string ImportCharSetDialogFilter {
            get {
                return ResourceManager.GetString("ImportCharSetDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported image from clipboard..
        /// </summary>
        public static string ImportedFromClipboard {
            get {
                return ResourceManager.GetString("ImportedFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from clipboard.
        /// </summary>
        public static string ImportFromClipboard {
            get {
                return ResourceManager.GetString("ImportFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import from clipboard: The text on clipboard is not a valid file path..
        /// </summary>
        public static string InvalidFilePath {
            get {
                return ResourceManager.GetString("InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert grayscale range.
        /// </summary>
        public static string InvertGrayscaleRange {
            get {
                return ResourceManager.GetString("InvertGrayscaleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep aspect ratio of the image.
        /// </summary>
        public static string KeepAspectRatio {
            get {
                return ResourceManager.GetString("KeepAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed to English. .
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon linkactivated {
            get {
                object obj = ResourceManager.GetObject("linkactivated", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon locale {
            get {
                object obj = ResourceManager.GetObject("locale", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open character set folder....
        /// </summary>
        public static string OpenCharSetFolder {
            get {
                return ResourceManager.GetString("OpenCharSetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file....
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP files (*.bmp)|*.bmp|JPEG files (*.jpg; *.jpeg)|*.jpg; *.jpeg|JPEG XR files (*.jxr)|*.jxr|PNG files (*.png)|*.png|TIFF files (*.tif; *.tiff)|*.tif; *.tiff|GIF files (*.gif)|*.gif|Icon files (*.ico)|*.ico|All supported files (*.bmp; *.jpg; *.jpeg; *.jxr; *.png; *.tif; *.tiff; *.gif; *.ico)|*.bmp; *.jpg; *.jpeg; *.jxr; *.png; *.tif; *.tiff; *.gif; *.ico.
        /// </summary>
        public static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon rubberduck {
            get {
                object obj = ResourceManager.GetObject("rubberduck", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text saved successfully. .
        /// </summary>
        public static string SavedToFile {
            get {
                return ResourceManager.GetString("SavedToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        public static string SaveFileDialogFilter {
            get {
                return ResourceManager.GetString("SaveFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant view - ASCIIsome.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import from clipboard: The file on clipboard is of unsupported type. .
        /// </summary>
        public static string UnsupportedType {
            get {
                return ResourceManager.GetString("UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ASCIIsome! See About window for more information. .
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
